version: '3.8'
include:
  - ./compose.traefik.yml

services:
  frontend:
    build: ./frontend
    #image: frontend
    ports:
      - "8080:8080"
    depends_on:
      - auth-api
      - todos-api
      - users-api
    environment:
      NODE_ENV: "development"
      PORT: ${PORT}
      AUTH_API_ADDRESS: ${AUTH_API_ADDRESS}
      TODOS_API_ADDRESS: ${TODOS_API_ADDRESS}
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`hngtodo.duckdns.org`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt" 
      - "traefik.http.services.frontend.loadbalancer.server.port=8080"

  auth-api:
    build: ./auth-api
    ports:
      - "8081:8081"
    environment:
      AUTH_API_PORT: ${AUTH_API_PORT}
      JWT_SECRET: ${JWT_SECRET}
      USERS_API_ADDRESS: ${USERS_API_ADDRESS}
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Host(`hngtodo.duckdns.org`) && PathPrefix(`/api/auth`)"
      - "traefik.http.routers.auth.entrypoints=websecure"
      - "traefik.http.routers.auth.tls.certresolver=letsencrypt"
      - "traefik.http.services.auth.loadbalancer.server.port=8081"
    
  todos-api:
    build: ./todos-api
    ports:
      - "8082:8082"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_CHANNEL: ${REDIS_CHANNEL}
    depends_on:
      - redis
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.todos.rule=Host(`hngtodo.duckdns.org`) && PathPrefix(`/api/todos`)"
      - "traefik.http.routers.todos.entrypoints=websecure"
      - "traefik.http.routers.todos.tls.certresolver=letsencrypt"
      - "traefik.http.services.todos.loadbalancer.server.port=8082"

  users-api:
    build: ./users-api
    ports:
      - "8083:8083"
    environment:
      SERVER_PORT: ${SERVER_PORT}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.users.rule=Host(`hngtodo.duckdns.org`) && PathPrefix(`/api/users`)"
      - "traefik.http.routers.users.entrypoints=websecure"
      - "traefik.http.routers.users.tls.certresolver=letsencrypt"
      - "traefik.http.services.users.loadbalancer.server.port=8083"
  

  log-processor:
    build: ./log-message-processor
    ports:
      - "6000:6000"
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_CHANNEL: ${REDIS_CHANNEL}
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

  networks:
  app-network:
    external: true
