version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - auth-api
      - todos-api
      - users-api

  auth-api:
    build: ./auth-api
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/auth_db
    depends_on:
      - db

  todos-api:
    build: ./todos-api
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  users-api:
    build: ./users-api
    ports:
      - "8081:8081"
    depends_on:
      - db

  log-processor:
    build: ./log-message-processor
    ports:
      - "6000:6000"
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - "6379:6379"

  db:
    image: "postgres:15"
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"

