version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - auth-api
      - todos-api
      - users-api
    environment:
      NODE_ENV: "development"
      PORT: ${PORT}
      AUTH_API_ADDRESS: ${AUTH_API_ADDRESS}
      TODOS_API_ADDRESS: ${TODOS_API_ADDRESS}

  auth-api:
    build: ./auth-api
    ports:
      - "8081:8081"
    environment:
      AUTH_API_PORT: ${AUTH_API_PORT}
      JWT_SECRET: ${JWT_SECRET}
      USERS_API_ADDRESS: ${USERS_API_ADDRESS}
    depends_on:
      - db

  todos-api:
    build: ./todos-api
    ports:
      - "8082:8082"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_CHANNEL: ${REDIS_CHANNEL}
    depends_on:
      - redis

  users-api:
    build: ./users-api
    ports:
      - "8083:8083"
    environment:
      SERVER_PORT: ${SERVER_PORT}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db

  log-processor:
    build: ./log-message-processor
    ports:
      - "6000:6000"
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_CHANNEL: ${REDIS_CHANNEL}
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - "6379:6379"
